#!/bin/sh

set -e

msg() {
	echo "odroid-wiringpi: $1"
}

case "$1" in
	purge)
		rm -f /etc/udev/rules.d/10-odroid-periphs.rules
		rm -f /etc/udev/rules.d/99-odroid-wiringpi-*

		msg "Reload udev..."
		[ -x "$(command -v udevadm)" ] \
			&& udevadm trigger \
			|| msg "udevadm not found. Please reboot to take effect"
	;;

	remove|upgrade|failed-upgrade|abort-install|abort-upgrade|disappear)
	;;

	*)
		echo "postrm called with unknown argument \`$1'" >&2
		exit 1
	;;
esac

exit 0
